import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import projectsRouter from "./projects";
import teamRouter from "./team";
import clientsRouter from "./clients";
import invoicesRouter from "./invoices";
import expensesRouter from "./expenses";
import dashboardRouter from "./dashboard";
import cmsRouter from "./cms";
import coursesRouter from "./courses";
import crewRouter from "./crew";
import calendarRouter from "./calendar";
import paymentSettingsRouter from "./payment-settings";
import aiRouter from "./ai";
import uploadsRouter from "./uploads";
import siteVideosRouter from "./site-videos";
import siteLogosRouter from "./site-logos";
import digitalAssetsRouter from "./digital-assets";
import paymentsRouter from "./payments";
import chatRouter from "./chat";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(projectsRouter);
router.use(teamRouter);
router.use(clientsRouter);
router.use(invoicesRouter);
router.use(expensesRouter);
router.use(dashboardRouter);
router.use(cmsRouter);
router.use(coursesRouter);
router.use(crewRouter);
router.use(calendarRouter);
router.use(paymentSettingsRouter);
router.use(aiRouter);
router.use(uploadsRouter);
router.use(siteVideosRouter);
router.use(siteLogosRouter);
router.use(digitalAssetsRouter);
router.use(paymentsRouter);
router.use("/", chatRouter);

export default router;
